//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveYourRecipes.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveYourRecipes.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentación de SQLite.
        /// </summary>
        internal static string acercadeview_cuarto_texto {
            get {
                return ResourceManager.GetString("acercadeview_cuarto_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://sqlite.org/docs.html.
        /// </summary>
        internal static string acercadeview_cuarto_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_cuarto_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación creada por Jorge Torres Padrón usando Xamarin Forms y SQLite.
        /// </summary>
        internal static string acercadeview_primer_texto {
            get {
                return ResourceManager.GetString("acercadeview_primer_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sígueme en GitHub.
        /// </summary>
        internal static string acercadeview_segundo_texto {
            get {
                return ResourceManager.GetString("acercadeview_segundo_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://github.com/JorgeTorresPadron.
        /// </summary>
        internal static string acercadeview_segundo_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_segundo_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentación de Xamarin Forms.
        /// </summary>
        internal static string acercadeview_tercer_texto {
            get {
                return ResourceManager.GetString("acercadeview_tercer_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://docs.microsoft.com/es-es/xamarin/xamarin-forms/.
        /// </summary>
        internal static string acercadeview_tercer_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_tercer_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de....
        /// </summary>
        internal static string configuracionview_acerca_de {
            get {
                return ResourceManager.GetString("configuracionview_acerca_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar idioma.
        /// </summary>
        internal static string configurationview_cambiar_idioma {
            get {
                return ResourceManager.GetString("configurationview_cambiar_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona la categoría a la que pertenece.
        /// </summary>
        internal static string nuevarecetaview_categoria_comida {
            get {
                return ResourceManager.GetString("nuevarecetaview_categoria_comida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe los pasos de la receta.
        /// </summary>
        internal static string nuevarecetaview_descripcion_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_descripcion_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Receta.
        /// </summary>
        internal static string nuevarecetaview_guardar_nueva_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_guardar_nueva_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona los ingredientes de la receta.
        /// </summary>
        internal static string nuevarecetaview_ingredientes_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_ingredientes_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el nombre de la receta.
        /// </summary>
        internal static string nuevarecetaview_nombre_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_nombre_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una nueva receta.
        /// </summary>
        internal static string nuevarecetaview_nueva_receta_label {
            get {
                return ResourceManager.GetString("nuevarecetaview_nueva_receta_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el tiempo de cocina de la receta.
        /// </summary>
        internal static string nuevarecetaview_tiempo_cocina {
            get {
                return ResourceManager.GetString("nuevarecetaview_tiempo_cocina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el tiempo de preparación de la receta.
        /// </summary>
        internal static string nuevarecetaview_tiempo_preparacion {
            get {
                return ResourceManager.GetString("nuevarecetaview_tiempo_preparacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string tabbed_page_configuracion_title {
            get {
                return ResourceManager.GetString("tabbed_page_configuracion_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Recetas.
        /// </summary>
        internal static string tabbed_page_mis_recetas_title {
            get {
                return ResourceManager.GetString("tabbed_page_mis_recetas_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Receta.
        /// </summary>
        internal static string tabbed_page_nueva_receta_title {
            get {
                return ResourceManager.GetString("tabbed_page_nueva_receta_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al menú principal.
        /// </summary>
        internal static string volver_al_menu_principal_button {
            get {
                return ResourceManager.GetString("volver_al_menu_principal_button", resourceCulture);
            }
        }
    }
}
