//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveYourRecipes.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveYourRecipes.Strings.Strings.es", typeof(Strings_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentación de SQLite.
        /// </summary>
        internal static string acercadeview_cuarto_texto {
            get {
                return ResourceManager.GetString("acercadeview_cuarto_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sqlite.org/docs.html.
        /// </summary>
        internal static string acercadeview_cuarto_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_cuarto_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponible en los idiomas siguientes.
        /// </summary>
        internal static string acercadeview_idiomas_disponibles {
            get {
                return ResourceManager.GetString("acercadeview_idiomas_disponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación para almacenar recetas de comida creada por Jorge Torres Padrón usando Xamarin Forms y SQLite para el proyecto final del ciclo de desarrollo de aplicaciones multiplataforma.
        /// </summary>
        internal static string acercadeview_primer_texto {
            get {
                return ResourceManager.GetString("acercadeview_primer_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sígueme en GitHub.
        /// </summary>
        internal static string acercadeview_segundo_texto {
            get {
                return ResourceManager.GetString("acercadeview_segundo_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/JorgeTorresPadron.
        /// </summary>
        internal static string acercadeview_segundo_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_segundo_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentación de Xamarin Forms.
        /// </summary>
        internal static string acercadeview_tercer_texto {
            get {
                return ResourceManager.GetString("acercadeview_tercer_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.microsoft.com/es-es/xamarin/xamarin-forms/.
        /// </summary>
        internal static string acercadeview_tercer_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_tercer_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        internal static string cambiarcontrasenaview_cambiar_contrasena_button {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_cambiar_contrasena_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe la nueva contraseña del usuario.
        /// </summary>
        internal static string cambiarcontrasenaview_contrasena_entry {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string cambiarcontrasenaview_contrasena_label {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver al inicio de sesión.
        /// </summary>
        internal static string cambiarcontrasenaview_inicio_sesion_button {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_inicio_sesion_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repite la nueva contraseña de usuario.
        /// </summary>
        internal static string cambiarcontrasenaview_repetir_contrasena_entry {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_repetir_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBIAR CONTRASEÑA.
        /// </summary>
        internal static string cambiarcontrasenaview_titulo {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe el nombre de usuario.
        /// </summary>
        internal static string cambiarcontrasenaview_usuario_entry {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_usuario_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        internal static string cambiarcontrasenaview_usuario_label {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_usuario_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de....
        /// </summary>
        internal static string configuracionview_acerca_de {
            get {
                return ResourceManager.GetString("configuracionview_acerca_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURACIÓN.
        /// </summary>
        internal static string configuracionview_configuracion_label {
            get {
                return ResourceManager.GetString("configuracionview_configuracion_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        internal static string configurationview_cerrar_sesion {
            get {
                return ResourceManager.GetString("configurationview_cerrar_sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar mi usuario.
        /// </summary>
        internal static string configurationview_eliminar_usuario {
            get {
                return ResourceManager.GetString("configurationview_eliminar_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string display_alert_aceptar {
            get {
                return ResourceManager.GetString("display_alert_aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario al que intentas cambiar la contraseña no existe.
        /// </summary>
        internal static string display_alert_cant_change_password_user_not_exist {
            get {
                return ResourceManager.GetString("display_alert_cant_change_password_user_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría eliminada correctamente.
        /// </summary>
        internal static string display_alert_category_deleted {
            get {
                return ResourceManager.GetString("display_alert_category_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría almacenada correctamente.
        /// </summary>
        internal static string display_alert_category_stored {
            get {
                return ResourceManager.GetString("display_alert_category_stored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría modificada correctamente.
        /// </summary>
        internal static string display_alert_category_updated {
            get {
                return ResourceManager.GetString("display_alert_category_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País eliminado correctamente.
        /// </summary>
        internal static string display_alert_country_deleted {
            get {
                return ResourceManager.GetString("display_alert_country_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País almacenado correctamente.
        /// </summary>
        internal static string display_alert_country_stored_correctly {
            get {
                return ResourceManager.GetString("display_alert_country_stored_correctly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País modificado correctamente.
        /// </summary>
        internal static string display_alert_country_updated {
            get {
                return ResourceManager.GetString("display_alert_country_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario que intentas eliminar no existe.
        /// </summary>
        internal static string display_alert_delete_user_not_exist {
            get {
                return ResourceManager.GetString("display_alert_delete_user_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado.
        /// </summary>
        internal static string display_alert_eliminado {
            get {
                return ResourceManager.GetString("display_alert_eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes escribir el tiempo de cocina de la receta.
        /// </summary>
        internal static string display_alert_empty_recipe_cooking_time {
            get {
                return ResourceManager.GetString("display_alert_empty_recipe_cooking_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes escribir una descripción para la receta.
        /// </summary>
        internal static string display_alert_empty_recipe_description {
            get {
                return ResourceManager.GetString("display_alert_empty_recipe_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes escribir los ingredientes de la receta.
        /// </summary>
        internal static string display_alert_empty_recipe_ingredients {
            get {
                return ResourceManager.GetString("display_alert_empty_recipe_ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes escribir un nombre para la receta.
        /// </summary>
        internal static string display_alert_empty_recipe_name {
            get {
                return ResourceManager.GetString("display_alert_empty_recipe_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes escribir el tiempo de preparación de la receta.
        /// </summary>
        internal static string display_alert_empty_recipe_preparation_time {
            get {
                return ResourceManager.GetString("display_alert_empty_recipe_preparation_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes escribir los pasos de la receta.
        /// </summary>
        internal static string display_alert_empty_recipe_steps {
            get {
                return ResourceManager.GetString("display_alert_empty_recipe_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string display_alert_error {
            get {
                return ResourceManager.GetString("display_alert_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar tu edad.
        /// </summary>
        internal static string display_alert_error_empty_age {
            get {
                return ResourceManager.GetString("display_alert_error_empty_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar tu nombre.
        /// </summary>
        internal static string display_alert_error_empty_firstname {
            get {
                return ResourceManager.GetString("display_alert_error_empty_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar tu apellido.
        /// </summary>
        internal static string display_alert_error_empty_lastname {
            get {
                return ResourceManager.GetString("display_alert_error_empty_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar una contraseña.
        /// </summary>
        internal static string display_alert_error_empty_password {
            get {
                return ResourceManager.GetString("display_alert_error_empty_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un nombre de usuario.
        /// </summary>
        internal static string display_alert_error_empty_username {
            get {
                return ResourceManager.GetString("display_alert_error_empty_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe o los datos introducidos son incorrectos.
        /// </summary>
        internal static string display_alert_error_iniciarsesionview {
            get {
                return ResourceManager.GetString("display_alert_error_iniciarsesionview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña repetida no es igual.
        /// </summary>
        internal static string display_alert_error_password_not_match {
            get {
                return ResourceManager.GetString("display_alert_error_password_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña de usuario actualizada.
        /// </summary>
        internal static string display_alert_password_updated {
            get {
                return ResourceManager.GetString("display_alert_password_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receta eliminada correctamente.
        /// </summary>
        internal static string display_alert_receta_eliminada {
            get {
                return ResourceManager.GetString("display_alert_receta_eliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receta.
        /// </summary>
        internal static string display_alert_recipe {
            get {
                return ResourceManager.GetString("display_alert_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to almacenada correctamente.
        /// </summary>
        internal static string display_alert_stored_correctly {
            get {
                return ResourceManager.GetString("display_alert_stored_correctly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éxito.
        /// </summary>
        internal static string display_alert_success {
            get {
                return ResourceManager.GetString("display_alert_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario eliminado correctamente.
        /// </summary>
        internal static string display_alert_user_delete_correctly {
            get {
                return ResourceManager.GetString("display_alert_user_delete_correctly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        internal static string display_alert_welcome {
            get {
                return ResourceManager.GetString("display_alert_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar cambios en la receta.
        /// </summary>
        internal static string editarrecetaview_actualizar_receta_button {
            get {
                return ResourceManager.GetString("editarrecetaview_actualizar_receta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar receta.
        /// </summary>
        internal static string editarrecetaview_actualizar_receta_label {
            get {
                return ResourceManager.GetString("editarrecetaview_actualizar_receta_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Atención! Esta acción no es reversible si borras el usuario perderás los datos de la aplicación.
        /// </summary>
        internal static string eliminarusuarioview_advertencia_label {
            get {
                return ResourceManager.GetString("eliminarusuarioview_advertencia_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe tu contraseña de usuario.
        /// </summary>
        internal static string eliminarusuarioview_contrasena_entry {
            get {
                return ResourceManager.GetString("eliminarusuarioview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string eliminarusuarioview_contrasena_label {
            get {
                return ResourceManager.GetString("eliminarusuarioview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar mi usuario.
        /// </summary>
        internal static string eliminarusuarioview_eliminar_usuario_button {
            get {
                return ResourceManager.GetString("eliminarusuarioview_eliminar_usuario_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe tu nombre de usuario.
        /// </summary>
        internal static string eliminarusuarioview_nombre_entry {
            get {
                return ResourceManager.GetString("eliminarusuarioview_nombre_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        internal static string eliminarusuarioview_nombre_label {
            get {
                return ResourceManager.GetString("eliminarusuarioview_nombre_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINACIÓN DEL USUARIO.
        /// </summary>
        internal static string eliminarusuarioview_titulo {
            get {
                return ResourceManager.GetString("eliminarusuarioview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe la contraseña.
        /// </summary>
        internal static string iniciarsesionview_contrasena_entry {
            get {
                return ResourceManager.GetString("iniciarsesionview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string iniciarsesionview_contrasena_label {
            get {
                return ResourceManager.GetString("iniciarsesionview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesion.
        /// </summary>
        internal static string iniciarsesionview_iniciar_sesion_button {
            get {
                return ResourceManager.GetString("iniciarsesionview_iniciar_sesion_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes una cuenta? Registrate.
        /// </summary>
        internal static string iniciarsesionview_no_tiene_cuenta_button {
            get {
                return ResourceManager.GetString("iniciarsesionview_no_tiene_cuenta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe el nombre de usuario.
        /// </summary>
        internal static string iniciarsesionview_nombre_entry {
            get {
                return ResourceManager.GetString("iniciarsesionview_nombre_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        internal static string iniciarsesionview_nombre_label {
            get {
                return ResourceManager.GetString("iniciarsesionview_nombre_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste la contraseña?.
        /// </summary>
        internal static string iniciarsesionview_olvida_contrasena_button {
            get {
                return ResourceManager.GetString("iniciarsesionview_olvida_contrasena_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIA SESIÓN PARA CONTINUAR.
        /// </summary>
        internal static string iniciarsesionview_titulo {
            get {
                return ResourceManager.GetString("iniciarsesionview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar receta.
        /// </summary>
        internal static string misrecetasview_actualizar_receta_button {
            get {
                return ResourceManager.GetString("misrecetasview_actualizar_receta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar receta.
        /// </summary>
        internal static string misrecetasview_eliminar_receta_button {
            get {
                return ResourceManager.GetString("misrecetasview_eliminar_receta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIS RECETAS.
        /// </summary>
        internal static string misrecetasview_mis_recetas_label {
            get {
                return ResourceManager.GetString("misrecetasview_mis_recetas_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar recetas almacenadas.
        /// </summary>
        internal static string misrecetasview_mostrar_receta_button {
            get {
                return ResourceManager.GetString("misrecetasview_mostrar_receta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar categoría.
        /// </summary>
        internal static string nuevacategoriaview_eliminar_categoria_button {
            get {
                return ResourceManager.GetString("nuevacategoriaview_eliminar_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar categoría.
        /// </summary>
        internal static string nuevacategoriaview_modificar_categoria_button {
            get {
                return ResourceManager.GetString("nuevacategoriaview_modificar_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar categoría.
        /// </summary>
        internal static string nuevacategoriaview_nueva_categoria_button {
            get {
                return ResourceManager.GetString("nuevacategoriaview_nueva_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe la categoría que quieres añadir.
        /// </summary>
        internal static string nuevacategoriaview_nueva_categoria_entry {
            get {
                return ResourceManager.GetString("nuevacategoriaview_nueva_categoria_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÑADIR UNA NUEVA CATEGORÍA DE COMIDA.
        /// </summary>
        internal static string nuevacategoriaview_titulo {
            get {
                return ResourceManager.GetString("nuevacategoriaview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir categoría.
        /// </summary>
        internal static string nuevarecetaview_anadir_categoria_button {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la categoría.
        /// </summary>
        internal static string nuevarecetaview_anadir_categoria_picker {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_categoria_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir país.
        /// </summary>
        internal static string nuevarecetaview_anadir_pais_button {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el país.
        /// </summary>
        internal static string nuevarecetaview_anadir_pais_picker {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_pais_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la categoría a la que pertenece.
        /// </summary>
        internal static string nuevarecetaview_categoria_comida {
            get {
                return ResourceManager.GetString("nuevarecetaview_categoria_comida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe la descripción de la receta.
        /// </summary>
        internal static string nuevarecetaview_descripcion_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_descripcion_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Receta.
        /// </summary>
        internal static string nuevarecetaview_guardar_nueva_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_guardar_nueva_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe los ingredientes de la receta.
        /// </summary>
        internal static string nuevarecetaview_ingredientes_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_ingredientes_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe el nombre de la receta.
        /// </summary>
        internal static string nuevarecetaview_nombre_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_nombre_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUEVA RECETA.
        /// </summary>
        internal static string nuevarecetaview_nueva_receta_label {
            get {
                return ResourceManager.GetString("nuevarecetaview_nueva_receta_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe los pasos de la receta.
        /// </summary>
        internal static string nuevarecetaview_pasos_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_pasos_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe el tiempo de cocina de la receta.
        /// </summary>
        internal static string nuevarecetaview_tiempo_cocina {
            get {
                return ResourceManager.GetString("nuevarecetaview_tiempo_cocina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe el tiempo de preparación de la receta.
        /// </summary>
        internal static string nuevarecetaview_tiempo_preparacion {
            get {
                return ResourceManager.GetString("nuevarecetaview_tiempo_preparacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar país.
        /// </summary>
        internal static string nuevopaisview_eliminar_pais_button {
            get {
                return ResourceManager.GetString("nuevopaisview_eliminar_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar país.
        /// </summary>
        internal static string nuevopaisview_modificar_pais_button {
            get {
                return ResourceManager.GetString("nuevopaisview_modificar_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar país.
        /// </summary>
        internal static string nuevopaisview_nuevo_pais_button {
            get {
                return ResourceManager.GetString("nuevopaisview_nuevo_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe el país que quieres añadir.
        /// </summary>
        internal static string nuevopaisview_nuevo_pais_entry {
            get {
                return ResourceManager.GetString("nuevopaisview_nuevo_pais_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÑADIR UN PAÍS.
        /// </summary>
        internal static string nuevopaisview_titulo {
            get {
                return ResourceManager.GetString("nuevopaisview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe tu apellido.
        /// </summary>
        internal static string registrarseview_apellido_real_entry {
            get {
                return ResourceManager.GetString("registrarseview_apellido_real_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string registrarseview_apellido_real_label {
            get {
                return ResourceManager.GetString("registrarseview_apellido_real_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe la contraseña.
        /// </summary>
        internal static string registrarseview_contrasena_entry {
            get {
                return ResourceManager.GetString("registrarseview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string registrarseview_contrasena_label {
            get {
                return ResourceManager.GetString("registrarseview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe tu edad.
        /// </summary>
        internal static string registrarseview_edad_entry {
            get {
                return ResourceManager.GetString("registrarseview_edad_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad.
        /// </summary>
        internal static string registrarseview_edad_label {
            get {
                return ResourceManager.GetString("registrarseview_edad_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe el nombre de usuario.
        /// </summary>
        internal static string registrarseview_nombre_entry {
            get {
                return ResourceManager.GetString("registrarseview_nombre_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        internal static string registrarseview_nombre_label {
            get {
                return ResourceManager.GetString("registrarseview_nombre_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe tu nombre.
        /// </summary>
        internal static string registrarseview_nombre_real_entry {
            get {
                return ResourceManager.GetString("registrarseview_nombre_real_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string registrarseview_nombre_real_label {
            get {
                return ResourceManager.GetString("registrarseview_nombre_real_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string registrarseview_registrarse_button {
            get {
                return ResourceManager.GetString("registrarseview_registrarse_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repite la contraseña que acabas de escribir.
        /// </summary>
        internal static string registrarseview_repetir_contrasena_entry {
            get {
                return ResourceManager.GetString("registrarseview_repetir_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya tienes una cuenta? Inicia Sesión.
        /// </summary>
        internal static string registrarseview_tiene_cuenta_button {
            get {
                return ResourceManager.GetString("registrarseview_tiene_cuenta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREA UNA NUEVA CUENTA PARA CONTINUAR.
        /// </summary>
        internal static string registrarseview_titulo {
            get {
                return ResourceManager.GetString("registrarseview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string tabbed_page_configuracion_title {
            get {
                return ResourceManager.GetString("tabbed_page_configuracion_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Recetas.
        /// </summary>
        internal static string tabbed_page_mis_recetas_title {
            get {
                return ResourceManager.GetString("tabbed_page_mis_recetas_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Receta.
        /// </summary>
        internal static string tabbed_page_nueva_receta_title {
            get {
                return ResourceManager.GetString("tabbed_page_nueva_receta_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver al menú principal.
        /// </summary>
        internal static string volver_al_menu_principal_button {
            get {
                return ResourceManager.GetString("volver_al_menu_principal_button", resourceCulture);
            }
        }
    }
}
