//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveYourRecipes.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveYourRecipes.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentación de SQLite.
        /// </summary>
        internal static string acercadeview_cuarto_texto {
            get {
                return ResourceManager.GetString("acercadeview_cuarto_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://sqlite.org/docs.html.
        /// </summary>
        internal static string acercadeview_cuarto_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_cuarto_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponible en los idiomas siguientes.
        /// </summary>
        internal static string acercadeview_idiomas_disponibles {
            get {
                return ResourceManager.GetString("acercadeview_idiomas_disponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación creada por Jorge Torres Padrón usando Xamarin Forms y SQLite.
        /// </summary>
        internal static string acercadeview_primer_texto {
            get {
                return ResourceManager.GetString("acercadeview_primer_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sígueme en GitHub.
        /// </summary>
        internal static string acercadeview_segundo_texto {
            get {
                return ResourceManager.GetString("acercadeview_segundo_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://github.com/JorgeTorresPadron.
        /// </summary>
        internal static string acercadeview_segundo_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_segundo_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentación de Xamarin Forms.
        /// </summary>
        internal static string acercadeview_tercer_texto {
            get {
                return ResourceManager.GetString("acercadeview_tercer_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://docs.microsoft.com/es-es/xamarin/xamarin-forms/.
        /// </summary>
        internal static string acercadeview_tercer_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_tercer_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        internal static string cambiarcontrasenaview_cambiar_contrasena_button {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_cambiar_contrasena_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe la nueva contraseña del usuario.
        /// </summary>
        internal static string cambiarcontrasenaview_contrasena_entry {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string cambiarcontrasenaview_contrasena_label {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al inicio de sesión.
        /// </summary>
        internal static string cambiarcontrasenaview_inicio_sesion_button {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_inicio_sesion_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAMBIAR CONTRASEÑA.
        /// </summary>
        internal static string cambiarcontrasenaview_titulo {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el nombre de usuario.
        /// </summary>
        internal static string cambiarcontrasenaview_usuario_entry {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_usuario_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string cambiarcontrasenaview_usuario_label {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_usuario_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de....
        /// </summary>
        internal static string configuracionview_acerca_de {
            get {
                return ResourceManager.GetString("configuracionview_acerca_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIGURACIÓN.
        /// </summary>
        internal static string configuracionview_configuracion_label {
            get {
                return ResourceManager.GetString("configuracionview_configuracion_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string configurationview_cerrar_sesion {
            get {
                return ResourceManager.GetString("configurationview_cerrar_sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar mi usuario.
        /// </summary>
        internal static string configurationview_eliminar_usuario {
            get {
                return ResourceManager.GetString("configurationview_eliminar_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar cambios en la receta.
        /// </summary>
        internal static string editarrecetaview_actualizar_receta_button {
            get {
                return ResourceManager.GetString("editarrecetaview_actualizar_receta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar receta.
        /// </summary>
        internal static string editarrecetaview_actualizar_receta_label {
            get {
                return ResourceManager.GetString("editarrecetaview_actualizar_receta_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu contraseña de usuario.
        /// </summary>
        internal static string eliminarusuarioview_contrasena_entry {
            get {
                return ResourceManager.GetString("eliminarusuarioview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string eliminarusuarioview_contrasena_label {
            get {
                return ResourceManager.GetString("eliminarusuarioview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar mi usuario.
        /// </summary>
        internal static string eliminarusuarioview_eliminar_usuario_button {
            get {
                return ResourceManager.GetString("eliminarusuarioview_eliminar_usuario_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu nombre de usuario.
        /// </summary>
        internal static string eliminarusuarioview_nombre_entry {
            get {
                return ResourceManager.GetString("eliminarusuarioview_nombre_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string eliminarusuarioview_nombre_label {
            get {
                return ResourceManager.GetString("eliminarusuarioview_nombre_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINACIÓN DEL USUARIO.
        /// </summary>
        internal static string eliminarusuarioview_titulo {
            get {
                return ResourceManager.GetString("eliminarusuarioview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe la contraseña.
        /// </summary>
        internal static string iniciarsesionview_contrasena_entry {
            get {
                return ResourceManager.GetString("iniciarsesionview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string iniciarsesionview_contrasena_label {
            get {
                return ResourceManager.GetString("iniciarsesionview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        internal static string iniciarsesionview_iniciar_sesion_button {
            get {
                return ResourceManager.GetString("iniciarsesionview_iniciar_sesion_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes una cuenta? Registrate.
        /// </summary>
        internal static string iniciarsesionview_no_tiene_cuenta_button {
            get {
                return ResourceManager.GetString("iniciarsesionview_no_tiene_cuenta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el nombre de usuario.
        /// </summary>
        internal static string iniciarsesionview_nombre_entry {
            get {
                return ResourceManager.GetString("iniciarsesionview_nombre_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string iniciarsesionview_nombre_label {
            get {
                return ResourceManager.GetString("iniciarsesionview_nombre_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste la contraseña?.
        /// </summary>
        internal static string iniciarsesionview_olvida_contrasena_button {
            get {
                return ResourceManager.GetString("iniciarsesionview_olvida_contrasena_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIA SESIÓN PARA CONTINUAR.
        /// </summary>
        internal static string iniciarsesionview_titulo {
            get {
                return ResourceManager.GetString("iniciarsesionview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar recetas.
        /// </summary>
        internal static string misrecetasview_eliminar_receta {
            get {
                return ResourceManager.GetString("misrecetasview_eliminar_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MIS RECETAS.
        /// </summary>
        internal static string misrecetasview_mis_recetas_label {
            get {
                return ResourceManager.GetString("misrecetasview_mis_recetas_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar recetas almacenadas.
        /// </summary>
        internal static string misrecetasview_mostrar_receta {
            get {
                return ResourceManager.GetString("misrecetasview_mostrar_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar categoría.
        /// </summary>
        internal static string nuevacategoriaview_eliminar_categoria_button {
            get {
                return ResourceManager.GetString("nuevacategoriaview_eliminar_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar categoría.
        /// </summary>
        internal static string nuevacategoriaview_modificar_categoria_button {
            get {
                return ResourceManager.GetString("nuevacategoriaview_modificar_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar categoría.
        /// </summary>
        internal static string nuevacategoriaview_nueva_categoria_button {
            get {
                return ResourceManager.GetString("nuevacategoriaview_nueva_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe la categoría que quieres añadir.
        /// </summary>
        internal static string nuevacategoriaview_nueva_categoria_entry {
            get {
                return ResourceManager.GetString("nuevacategoriaview_nueva_categoria_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AÑADIR UNA NUEVA CATEGORÍA DE COMIDA.
        /// </summary>
        internal static string nuevacategoriaview_titulo {
            get {
                return ResourceManager.GetString("nuevacategoriaview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir categoría.
        /// </summary>
        internal static string nuevarecetaview_anadir_categoria_button {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona la categoría.
        /// </summary>
        internal static string nuevarecetaview_anadir_categoria_picker {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_categoria_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir país.
        /// </summary>
        internal static string nuevarecetaview_anadir_pais_button {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el país.
        /// </summary>
        internal static string nuevarecetaview_anadir_pais_picker {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_pais_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona la categoría a la que pertenece.
        /// </summary>
        internal static string nuevarecetaview_categoria_comida {
            get {
                return ResourceManager.GetString("nuevarecetaview_categoria_comida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe la descripción de la receta.
        /// </summary>
        internal static string nuevarecetaview_descripcion_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_descripcion_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Receta.
        /// </summary>
        internal static string nuevarecetaview_guardar_nueva_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_guardar_nueva_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe los ingredientes de la receta.
        /// </summary>
        internal static string nuevarecetaview_ingredientes_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_ingredientes_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el nombre de la receta.
        /// </summary>
        internal static string nuevarecetaview_nombre_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_nombre_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUEVA RECETA.
        /// </summary>
        internal static string nuevarecetaview_nueva_receta_label {
            get {
                return ResourceManager.GetString("nuevarecetaview_nueva_receta_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe los pasos de la receta.
        /// </summary>
        internal static string nuevarecetaview_pasos_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_pasos_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el tiempo de cocina de la receta.
        /// </summary>
        internal static string nuevarecetaview_tiempo_cocina {
            get {
                return ResourceManager.GetString("nuevarecetaview_tiempo_cocina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el tiempo de preparación de la receta.
        /// </summary>
        internal static string nuevarecetaview_tiempo_preparacion {
            get {
                return ResourceManager.GetString("nuevarecetaview_tiempo_preparacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar país.
        /// </summary>
        internal static string nuevopaisview_eliminar_pais_button {
            get {
                return ResourceManager.GetString("nuevopaisview_eliminar_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar país.
        /// </summary>
        internal static string nuevopaisview_modificar_pais_button {
            get {
                return ResourceManager.GetString("nuevopaisview_modificar_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar país.
        /// </summary>
        internal static string nuevopaisview_nuevo_pais_button {
            get {
                return ResourceManager.GetString("nuevopaisview_nuevo_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el país que quieres añadir.
        /// </summary>
        internal static string nuevopaisview_nuevo_pais_entry {
            get {
                return ResourceManager.GetString("nuevopaisview_nuevo_pais_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AÑADIR UN PAÍS.
        /// </summary>
        internal static string nuevopaisview_titulo {
            get {
                return ResourceManager.GetString("nuevopaisview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu apellido.
        /// </summary>
        internal static string registrarseview_apellido_real_entry {
            get {
                return ResourceManager.GetString("registrarseview_apellido_real_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string registrarseview_apellido_real_label {
            get {
                return ResourceManager.GetString("registrarseview_apellido_real_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe la contraseña.
        /// </summary>
        internal static string registrarseview_contrasena_entry {
            get {
                return ResourceManager.GetString("registrarseview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string registrarseview_contrasena_label {
            get {
                return ResourceManager.GetString("registrarseview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu edad.
        /// </summary>
        internal static string registrarseview_edad_entry {
            get {
                return ResourceManager.GetString("registrarseview_edad_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        internal static string registrarseview_edad_label {
            get {
                return ResourceManager.GetString("registrarseview_edad_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el nombre de usuario.
        /// </summary>
        internal static string registrarseview_nombre_entry {
            get {
                return ResourceManager.GetString("registrarseview_nombre_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string registrarseview_nombre_label {
            get {
                return ResourceManager.GetString("registrarseview_nombre_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu nombre.
        /// </summary>
        internal static string registrarseview_nombre_real_entry {
            get {
                return ResourceManager.GetString("registrarseview_nombre_real_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string registrarseview_nombre_real_label {
            get {
                return ResourceManager.GetString("registrarseview_nombre_real_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string registrarseview_registrarse_button {
            get {
                return ResourceManager.GetString("registrarseview_registrarse_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repite la contraseña que acabas de escribir.
        /// </summary>
        internal static string registrarseview_repetir_contrasena_entry {
            get {
                return ResourceManager.GetString("registrarseview_repetir_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes una cuenta? Inicia Sesión.
        /// </summary>
        internal static string registrarseview_tiene_cuenta_button {
            get {
                return ResourceManager.GetString("registrarseview_tiene_cuenta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREA UNA NUEVA CUENTA PARA CONTINUAR.
        /// </summary>
        internal static string registrarseview_titulo {
            get {
                return ResourceManager.GetString("registrarseview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string tabbed_page_configuracion_title {
            get {
                return ResourceManager.GetString("tabbed_page_configuracion_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Recetas.
        /// </summary>
        internal static string tabbed_page_mis_recetas_title {
            get {
                return ResourceManager.GetString("tabbed_page_mis_recetas_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Receta.
        /// </summary>
        internal static string tabbed_page_nueva_receta_title {
            get {
                return ResourceManager.GetString("tabbed_page_nueva_receta_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al menú principal.
        /// </summary>
        internal static string volver_al_menu_principal_button {
            get {
                return ResourceManager.GetString("volver_al_menu_principal_button", resourceCulture);
            }
        }
    }
}
