//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveYourRecipes.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveYourRecipes.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite Documentation.
        /// </summary>
        internal static string acercadeview_cuarto_texto {
            get {
                return ResourceManager.GetString("acercadeview_cuarto_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sqlite.org/docs.html.
        /// </summary>
        internal static string acercadeview_cuarto_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_cuarto_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available in the following languages.
        /// </summary>
        internal static string acercadeview_idiomas_disponibles {
            get {
                return ResourceManager.GetString("acercadeview_idiomas_disponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application to store food recipes created by Jorge Torres Padrón using Xamarin Forms and SQLite for the final project of the cross-platform application development cycle.
        /// </summary>
        internal static string acercadeview_primer_texto {
            get {
                return ResourceManager.GetString("acercadeview_primer_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow me on GitHub.
        /// </summary>
        internal static string acercadeview_segundo_texto {
            get {
                return ResourceManager.GetString("acercadeview_segundo_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/JorgeTorresPadron.
        /// </summary>
        internal static string acercadeview_segundo_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_segundo_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin Forms Documentation.
        /// </summary>
        internal static string acercadeview_tercer_texto {
            get {
                return ResourceManager.GetString("acercadeview_tercer_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.microsoft.com/en-us/xamarin/xamarin-forms/.
        /// </summary>
        internal static string acercadeview_tercer_texto_link {
            get {
                return ResourceManager.GetString("acercadeview_tercer_texto_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string cambiarcontrasenaview_cambiar_contrasena_button {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_cambiar_contrasena_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the user&apos;s new password.
        /// </summary>
        internal static string cambiarcontrasenaview_contrasena_entry {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string cambiarcontrasenaview_contrasena_label {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        internal static string cambiarcontrasenaview_inicio_sesion_button {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_inicio_sesion_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the new user password.
        /// </summary>
        internal static string cambiarcontrasenaview_repetir_contrasena_entry {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_repetir_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PASSWORD.
        /// </summary>
        internal static string cambiarcontrasenaview_titulo {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username.
        /// </summary>
        internal static string cambiarcontrasenaview_usuario_entry {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_usuario_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string cambiarcontrasenaview_usuario_label {
            get {
                return ResourceManager.GetString("cambiarcontrasenaview_usuario_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string configuracionview_acerca_de {
            get {
                return ResourceManager.GetString("configuracionview_acerca_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURATION.
        /// </summary>
        internal static string configuracionview_configuracion_label {
            get {
                return ResourceManager.GetString("configuracionview_configuracion_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string configurationview_cerrar_sesion {
            get {
                return ResourceManager.GetString("configurationview_cerrar_sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my username.
        /// </summary>
        internal static string configurationview_eliminar_usuario {
            get {
                return ResourceManager.GetString("configurationview_eliminar_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string display_alert_aceptar {
            get {
                return ResourceManager.GetString("display_alert_aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you are trying to change the password does not exist.
        /// </summary>
        internal static string display_alert_cant_change_password_user_not_exist {
            get {
                return ResourceManager.GetString("display_alert_cant_change_password_user_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted category.
        /// </summary>
        internal static string display_alert_category_deleted {
            get {
                return ResourceManager.GetString("display_alert_category_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully stored category.
        /// </summary>
        internal static string display_alert_category_stored {
            get {
                return ResourceManager.GetString("display_alert_category_stored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified category.
        /// </summary>
        internal static string display_alert_category_updated {
            get {
                return ResourceManager.GetString("display_alert_category_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you are trying to delete does not exist.
        /// </summary>
        internal static string display_alert_delete_user_not_exist {
            get {
                return ResourceManager.GetString("display_alert_delete_user_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string display_alert_eliminado {
            get {
                return ResourceManager.GetString("display_alert_eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string display_alert_error {
            get {
                return ResourceManager.GetString("display_alert_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your age.
        /// </summary>
        internal static string display_alert_error_empty_age {
            get {
                return ResourceManager.GetString("display_alert_error_empty_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your first name.
        /// </summary>
        internal static string display_alert_error_empty_firstname {
            get {
                return ResourceManager.GetString("display_alert_error_empty_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your last name.
        /// </summary>
        internal static string display_alert_error_empty_lastname {
            get {
                return ResourceManager.GetString("display_alert_error_empty_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password.
        /// </summary>
        internal static string display_alert_error_empty_password {
            get {
                return ResourceManager.GetString("display_alert_error_empty_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a user name.
        /// </summary>
        internal static string display_alert_error_empty_username {
            get {
                return ResourceManager.GetString("display_alert_error_empty_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user doesn&apos;t exist or the introduced data is incorrect.
        /// </summary>
        internal static string display_alert_error_iniciarsesionview {
            get {
                return ResourceManager.GetString("display_alert_error_iniciarsesionview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated password is not the same.
        /// </summary>
        internal static string display_alert_error_password_not_match {
            get {
                return ResourceManager.GetString("display_alert_error_password_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated user password.
        /// </summary>
        internal static string display_alert_password_updated {
            get {
                return ResourceManager.GetString("display_alert_password_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe deleted correctly.
        /// </summary>
        internal static string display_alert_receta_eliminada {
            get {
                return ResourceManager.GetString("display_alert_receta_eliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string display_alert_success {
            get {
                return ResourceManager.GetString("display_alert_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully deleted.
        /// </summary>
        internal static string display_alert_user_delete_correctly {
            get {
                return ResourceManager.GetString("display_alert_user_delete_correctly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string display_alert_welcome {
            get {
                return ResourceManager.GetString("display_alert_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update recipe changes.
        /// </summary>
        internal static string editarrecetaview_actualizar_receta_button {
            get {
                return ResourceManager.GetString("editarrecetaview_actualizar_receta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update recipe.
        /// </summary>
        internal static string editarrecetaview_actualizar_receta_label {
            get {
                return ResourceManager.GetString("editarrecetaview_actualizar_receta_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! This action is not reversible if you delete the user you will lose the application data.
        /// </summary>
        internal static string eliminarusuarioview_advertencia_label {
            get {
                return ResourceManager.GetString("eliminarusuarioview_advertencia_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your user password.
        /// </summary>
        internal static string eliminarusuarioview_contrasena_entry {
            get {
                return ResourceManager.GetString("eliminarusuarioview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string eliminarusuarioview_contrasena_label {
            get {
                return ResourceManager.GetString("eliminarusuarioview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my username.
        /// </summary>
        internal static string eliminarusuarioview_eliminar_usuario_button {
            get {
                return ResourceManager.GetString("eliminarusuarioview_eliminar_usuario_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        internal static string eliminarusuarioview_nombre_entry {
            get {
                return ResourceManager.GetString("eliminarusuarioview_nombre_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string eliminarusuarioview_nombre_label {
            get {
                return ResourceManager.GetString("eliminarusuarioview_nombre_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER DELETION.
        /// </summary>
        internal static string eliminarusuarioview_titulo {
            get {
                return ResourceManager.GetString("eliminarusuarioview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string iniciarsesionview_contrasena_entry {
            get {
                return ResourceManager.GetString("iniciarsesionview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string iniciarsesionview_contrasena_label {
            get {
                return ResourceManager.GetString("iniciarsesionview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string iniciarsesionview_iniciar_sesion_button {
            get {
                return ResourceManager.GetString("iniciarsesionview_iniciar_sesion_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Sign in.
        /// </summary>
        internal static string iniciarsesionview_no_tiene_cuenta_button {
            get {
                return ResourceManager.GetString("iniciarsesionview_no_tiene_cuenta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username.
        /// </summary>
        internal static string iniciarsesionview_nombre_entry {
            get {
                return ResourceManager.GetString("iniciarsesionview_nombre_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string iniciarsesionview_nombre_label {
            get {
                return ResourceManager.GetString("iniciarsesionview_nombre_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string iniciarsesionview_olvida_contrasena_button {
            get {
                return ResourceManager.GetString("iniciarsesionview_olvida_contrasena_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN TO CONTINUE.
        /// </summary>
        internal static string iniciarsesionview_titulo {
            get {
                return ResourceManager.GetString("iniciarsesionview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update recipe.
        /// </summary>
        internal static string misrecetasview_actualizar_receta_button {
            get {
                return ResourceManager.GetString("misrecetasview_actualizar_receta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove recipe.
        /// </summary>
        internal static string misrecetasview_eliminar_receta_button {
            get {
                return ResourceManager.GetString("misrecetasview_eliminar_receta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY RECIPES.
        /// </summary>
        internal static string misrecetasview_mis_recetas_label {
            get {
                return ResourceManager.GetString("misrecetasview_mis_recetas_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show stored recipes.
        /// </summary>
        internal static string misrecetasview_mostrar_receta_button {
            get {
                return ResourceManager.GetString("misrecetasview_mostrar_receta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete category.
        /// </summary>
        internal static string nuevacategoriaview_eliminar_categoria_button {
            get {
                return ResourceManager.GetString("nuevacategoriaview_eliminar_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify category.
        /// </summary>
        internal static string nuevacategoriaview_modificar_categoria_button {
            get {
                return ResourceManager.GetString("nuevacategoriaview_modificar_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save category.
        /// </summary>
        internal static string nuevacategoriaview_nueva_categoria_button {
            get {
                return ResourceManager.GetString("nuevacategoriaview_nueva_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the category you want to add.
        /// </summary>
        internal static string nuevacategoriaview_nueva_categoria_entry {
            get {
                return ResourceManager.GetString("nuevacategoriaview_nueva_categoria_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD A NEW FOOD CATEGORY.
        /// </summary>
        internal static string nuevacategoriaview_titulo {
            get {
                return ResourceManager.GetString("nuevacategoriaview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        internal static string nuevarecetaview_anadir_categoria_button {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_categoria_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the category.
        /// </summary>
        internal static string nuevarecetaview_anadir_categoria_picker {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_categoria_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add country.
        /// </summary>
        internal static string nuevarecetaview_anadir_pais_button {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the country.
        /// </summary>
        internal static string nuevarecetaview_anadir_pais_picker {
            get {
                return ResourceManager.GetString("nuevarecetaview_anadir_pais_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the category to which it belongs.
        /// </summary>
        internal static string nuevarecetaview_categoria_comida {
            get {
                return ResourceManager.GetString("nuevarecetaview_categoria_comida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the recipe description.
        /// </summary>
        internal static string nuevarecetaview_descripcion_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_descripcion_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Recipe.
        /// </summary>
        internal static string nuevarecetaview_guardar_nueva_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_guardar_nueva_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the ingredients of the recipe.
        /// </summary>
        internal static string nuevarecetaview_ingredientes_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_ingredientes_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the recipe.
        /// </summary>
        internal static string nuevarecetaview_nombre_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_nombre_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW RECIPE.
        /// </summary>
        internal static string nuevarecetaview_nueva_receta_label {
            get {
                return ResourceManager.GetString("nuevarecetaview_nueva_receta_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the steps of the recipe.
        /// </summary>
        internal static string nuevarecetaview_pasos_receta {
            get {
                return ResourceManager.GetString("nuevarecetaview_pasos_receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write down the cooking time of the recipe.
        /// </summary>
        internal static string nuevarecetaview_tiempo_cocina {
            get {
                return ResourceManager.GetString("nuevarecetaview_tiempo_cocina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write down the recipe preparation time.
        /// </summary>
        internal static string nuevarecetaview_tiempo_preparacion {
            get {
                return ResourceManager.GetString("nuevarecetaview_tiempo_preparacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete country.
        /// </summary>
        internal static string nuevopaisview_eliminar_pais_button {
            get {
                return ResourceManager.GetString("nuevopaisview_eliminar_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify country.
        /// </summary>
        internal static string nuevopaisview_modificar_pais_button {
            get {
                return ResourceManager.GetString("nuevopaisview_modificar_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save country.
        /// </summary>
        internal static string nuevopaisview_nuevo_pais_button {
            get {
                return ResourceManager.GetString("nuevopaisview_nuevo_pais_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the country you want to add.
        /// </summary>
        internal static string nuevopaisview_nuevo_pais_entry {
            get {
                return ResourceManager.GetString("nuevopaisview_nuevo_pais_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD A COUNTRY.
        /// </summary>
        internal static string nuevopaisview_titulo {
            get {
                return ResourceManager.GetString("nuevopaisview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your last name.
        /// </summary>
        internal static string registrarseview_apellido_real_entry {
            get {
                return ResourceManager.GetString("registrarseview_apellido_real_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string registrarseview_apellido_real_label {
            get {
                return ResourceManager.GetString("registrarseview_apellido_real_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string registrarseview_contrasena_entry {
            get {
                return ResourceManager.GetString("registrarseview_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string registrarseview_contrasena_label {
            get {
                return ResourceManager.GetString("registrarseview_contrasena_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your age.
        /// </summary>
        internal static string registrarseview_edad_entry {
            get {
                return ResourceManager.GetString("registrarseview_edad_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string registrarseview_edad_label {
            get {
                return ResourceManager.GetString("registrarseview_edad_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username.
        /// </summary>
        internal static string registrarseview_nombre_entry {
            get {
                return ResourceManager.GetString("registrarseview_nombre_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string registrarseview_nombre_label {
            get {
                return ResourceManager.GetString("registrarseview_nombre_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your first name.
        /// </summary>
        internal static string registrarseview_nombre_real_entry {
            get {
                return ResourceManager.GetString("registrarseview_nombre_real_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string registrarseview_nombre_real_label {
            get {
                return ResourceManager.GetString("registrarseview_nombre_real_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string registrarseview_registrarse_button {
            get {
                return ResourceManager.GetString("registrarseview_registrarse_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the password you just typed.
        /// </summary>
        internal static string registrarseview_repetir_contrasena_entry {
            get {
                return ResourceManager.GetString("registrarseview_repetir_contrasena_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Log in.
        /// </summary>
        internal static string registrarseview_tiene_cuenta_button {
            get {
                return ResourceManager.GetString("registrarseview_tiene_cuenta_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE A NEW ACCOUNT TO CONTINUE.
        /// </summary>
        internal static string registrarseview_titulo {
            get {
                return ResourceManager.GetString("registrarseview_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string tabbed_page_configuracion_title {
            get {
                return ResourceManager.GetString("tabbed_page_configuracion_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Recipes.
        /// </summary>
        internal static string tabbed_page_mis_recetas_title {
            get {
                return ResourceManager.GetString("tabbed_page_mis_recetas_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recipe.
        /// </summary>
        internal static string tabbed_page_nueva_receta_title {
            get {
                return ResourceManager.GetString("tabbed_page_nueva_receta_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main menu.
        /// </summary>
        internal static string volver_al_menu_principal_button {
            get {
                return ResourceManager.GetString("volver_al_menu_principal_button", resourceCulture);
            }
        }
    }
}
